[book]
authors = ["Sangwoo Joh"]
language = "ko"
multilingual = true
src = "src"
title = "OCaml Problem Solving"

[output.html]
mathjax-support = true
google-analytics = "G-J0C68FHJ6L"
additional-css = ["custom.css"]
